### ISSUE TITLE
Issues with LiveChat.on("customer_profile", function) getting triggered

### ISSUE THREAD

**Issue by Gogoro** [livechat/agent-app-widget-sdk#19]
Hi!

I'm working on a LiveChat sidebar APP, and have gotten into some trouble with the "customer_profile" event.

I've followed the documentation on Github and NPM, and my code was working "as expected" at some point. But now it doesn't anymore... 😢 

I have tried to get it working for a while, and my code is getting messier and messier trying to figure it out, but I'm starting to suspect it being a bug on your part?

## What I'm trying to do:

```JavaScript
import LiveChat from '@livechat/agent-app-widget-sdk'

LiveChat.init()
LiveChat.refreshSessionId()

LiveChat.on("customer_profile", data => {
  console.log('data', data)
  // Use the chat ID to do other calls.
})
```

### Image of my code:

> NB: I'm using React.

![image](https://user-images.githubusercontent.com/1327105/54126867-d2e28b00-4408-11e9-8fd9-15854b5189cf.png)

### Issue

The `LiveChat.on("customer_profile", function)` event listener is not getting triggered when i "open" the APP in the sidebar. Only when I "switch" between chats..

#### Can I get an answer for:
1. Do you have a better way to get the current "chat ID"?
2. How can I get this event listener to trigger?
3. Is it me or you? ;) 

Have a nice day!

**Comment by quarties** [comment]
Hi @Gogoro - could you try to put `LiveChat.refreshSessionId()` before declaring customer_profile event listener? Due to the technicalities of React, this method is required to receive the first event.

**Comment by quarties** [comment]
To answer your first question - customer profile event is the best and the most reliable way to acquire visitor/chat ID in Agent App Widget :-)

**Comment by Gogoro** [comment]
Hi @quarties and thanks for the reply!

I've tried what you said without success.

I changed my code to this to minimize the risk of any of my other code messing with the LiveChat flow.

![image](https://user-images.githubusercontent.com/1327105/54423468-0545fe00-4711-11e9-9b3d-34628d46cc1f.png)

This is the result when I try to load the app inside LiveChat:

![image](https://user-images.githubusercontent.com/1327105/54423374-d6c82300-4710-11e9-86f0-4bd00602da95.png)

The `console.log('data from "customer_profile"...', data)` does not get triggered.

Do you have any suggestions for what I should try next?

**Comment by quarties** [comment]
I made a simple example to confirm that everything works on our end - and it does, you can check my example here (you might need to download the project, as glitch has some performance problems): https://glitch.com/edit/#!/chalk-fight

If you still encounter this issue then please host your source code on glitch or codesandbox (or any other service) and share a link with us.

**Comment by Gogoro** [comment]
Hi again @quarties!

I tested your example, and that works well isolated. But after doing more testing I see that the issue is related to using LiveChat SSO with the SDK. 

If I try to remove the SSO logic I get the customer information. 

See the two examples bellow. the first one fails, and the second works well.

The code might not be super nice, but it shows the issue. 

### Example 1 (with SSO, fails)

``` JS
import React, { Component } from 'react'
import LiveChat from '@livechat/agent-app-widget-sdk'
import axios from 'axios'

const config = {
  appClientId: '' // enter appClientId
}


class App extends Component {
  constructor(props) {
    super(props)

    this.state = {
      token: null,
      errorMessage: null
    }
  }

  componentDidMount() {
     if (window.location.hash && window.location.hash.search('access_token') > -1) {
      // Set token if it's present in the URL
      axios.defaults.headers.common['livechat_token'] = `Bearer ${window.location.hash.substr(14).split('&')[0]}`
      this.setState({token: window.location.hash.substr(14).split('&')[0]}, () => {
        this.getChatinformation()
      })
    } else {
      // Get token if it's not present in the url
      if (window.location.hash.search('error') > -1) {
        this.setState({ errorMessage: 'Problem with authorization, please try to reload the app'})
      }
      else {
        console.log('  triggered refresh')
        window.location.href = `https://accounts.livechatinc.com/?response_type=token&client_id=${config.appClientId}&redirect_uri=${window.location.origin}`
      }
    }
  };

  getChatinformation = () => {
    console.log("LiveChat init")
    LiveChat.init()
    console.log('refreshing sessions id...')
    LiveChat.refreshSessionId()
    console.log('sessions id should be triggered...')

    console.log('Adding listener on "customer_profile"...')
    LiveChat.on("customer_profile", data => {
      console.log('data from "customer_profile"...', data)
    })

    console.log('Event listener for "customer_profile" should have been added...')
  };

  render() {
    if (this.state.token) {
      return <div>Logged in</div>;
    }
    return this.state.errorMessage ? (<p>{this.state.errorMessage}</p>) : (<p>Loading...</p>);
  }
}

export default App
```

### Example two (without SSO, works)

```JS
import React, { Component } from 'react'
import LiveChat from '@livechat/agent-app-widget-sdk'
import axios from 'axios'

const config = {
  appClientId: '' // enter appClientId
}

class App extends Component {
  constructor(props) {
    super(props)

    this.state = {
      token: null,
      errorMessage: null
    }
  }

  componentDidMount() {
    //  if (window.location.hash && window.location.hash.search('access_token') > -1) {
    //   // Set token if it's present in the URL
    //   axios.defaults.headers.common['livechat_token'] = `Bearer ${window.location.hash.substr(14).split('&')[0]}`
    //   this.setState({token: window.location.hash.substr(14).split('&')[0]}, () => {
        this.getChatinformation()
    //   })
    //   console.log('  found access_token')
    // } else {
    //   // Get token if it's not present in the url
    //   if (window.location.hash.search('error') > -1) {
    //     this.setState({ errorMessage: 'Problem with authorization, please try to reload the app'})
    //   }
    //   else {
    //     // LiveChat.init() // Only to please LiveChat (only needs to be triggered)
    //     console.log('  triggered refresh')
    //     window.location.href = `https://accounts.livechatinc.com/?response_type=token&client_id=${config.appClientId}&redirect_uri=${window.location.origin}`
    //   }
    // }
  };

  getChatinformation = () => {
    console.log("LiveChat init")
    LiveChat.init()
    console.log('refreshing sessions id...')
    LiveChat.refreshSessionId()
    console.log('sessions id should be triggered...')

    console.log('Adding listener on "customer_profile"...')
    LiveChat.on("customer_profile", data => {
      console.log('data from "customer_profile"...', data)
    })

    console.log('Event listener for "customer_profile" should have been added...')
  };

  render() {
    if (this.state.token) {
      console.log(this.state.token)
      return <Dashboard />;
    }
    return this.state.errorMessage ? (<p>{this.state.errorMessage}</p>) : (<p>Loading...</p>);
  }
}

export default App
```

**Comment by quarties** [comment]
@Gogoro thanks for more details. As far as I understood your code, you are trying to redirect user to LC accounts page, but it's not possible to iframe this page (due to our security rules).

Also, you should always load the Agent App Widget SDK in `componentDidMount` - it is fully independent from AccountsSDK or another form of LC SSO (or any other SSO as well).

If you would like to acquire LC access token, then the best is to use Accounts SDK - here are the docs: https://developers.livechatinc.com/docs/sign-in-with-livechat/
Our agent app will never pass the access token to your app - it's against OAuth 2.0 standard. That's why you need to get token on your own.

And here is a simple example that should work for ya:

```javascript
import React, { Component } from 'react';
import { accountsSdk } from '@livechat/accounts-sdk';
import LiveChat from '@livechat/agent-app-widget-sdk';

class App extends Component {
  constructor(props) {
    super(props);

    this.accountsInstance = null;
    this.clientID = '<your_client_id>';
    this.state = {
      profile: {},
      token: null
    }
  }

  componentDidMount() {
    console.log('LiveChat.init');
    LiveChat.init();
    console.log('LiveChat.refreshSessionId');
    LiveChat.refreshSessionId();

    LiveChat.on("customer_profile", profile => {
      console.log('customer_profile', profile);
      this.setState({ profile });
    });
    this.accountsInstance = accountsSdk.init({
      client_id: this.clientID,
      onIdentityFetched: (error, data) => {
        console.log('Identity fetched!');
        if(error) {
          console.log('Error:', error);
        }
        if(data) {
          console.log('Data:', data);
          this.setState({token: data.access_token});
        }
      }
    });
  }

  render() {
    return (
      <div className="App">
        <pre>{JSON.stringify(this.state.profile)}</pre>
        {this.state.token && <pre>Token: {this.state.token}</pre>}
        {!this.state.token && <div className="livechat-login-button" />}
        {this.state.token && (
          <button onClick={(e) => {
              e.preventDefault();

              this.accountsInstance.signOut(function() {
                  console.log('User signed out');
              });
          }}>Logout</button>
        )}
      </div>
    );
  }
}

export default App;
```

**Comment by Gogoro** [comment]
Hi @quarties!

Changing to the accounts SKD did the trick, thanks a lot!

Have a great day 😄 👍 👍

**Comment by quarties** [comment]
You're welcome :-) Feel free to reach our support team or create another issue here if you spot any further problems.
