### ISSUE TITLE
How to get customer messages?

### ISSUE THREAD

**Issue by rainmakerho** [livechat/agent-app-widget-sdk#23]
Hi, 
May I get customer messages on customer_profile event?
Thanks.

**Comment by venits** [comment]
Hi, there is a method `LiveChat.getMessages()` and it gets most recent messages. Those that were seny during current session. Messages **are not** passed with `customer_profile`.

If you want to get all message from conversation, you have to use our REST API.

**Comment by quarties** [comment]
Closing as @rainmakerho confirmed that everything works fine here: https://github.com/livechat/agent-app-widget-sdk/issues/16

**Comment by rainmakerho** [comment]
@venits ,
Thank you.
